[project]
name = "deeplearning3"
version = "0.1.0"
description = "Deep Learning From Scratch 3"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
]
